version: "3.7"
services:
  frontend:
    container_name: frontend
    restart: unless-stopped
    build: ./frontend
    ports:
      - 5173:5173
    env_file:
      - ./frontend/.env
    depends_on:
      - redis
      - postgres

  postgres:
    container_name: postgres
    restart: unless-stopped
    image: postgres:16-alpine
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - ./postgres-db:/var/lib/postgresql/data

  redis:
    container_name: redis
    image: redis:7-alpine
    restart: unless-stopped
    volumes:
      - ./redis-db:/data
    ports:
      - 6379:6379
