version: '3.7'
services:
  frontend:
    container_name: frontend
    restart: unless-stopped
    build: ./frontend
    ports:
      - 5173:5173
    volumes:
      - ~/AppData/Local/pnpm/store:/root/.pnpm-store # MacOS
      # - ~/.pnpm-store:/root/.pnpm-store # Linux
    env_file:
      - ./frontend/.env
    environment:
      PRIVATE_REDIS_URL: redis://redis:6379

  redis:
    container_name: redis
    image: redis:alpine
    restart: unless-stopped
    volumes:
      - ./redis-db:/data
    ports:
      - 6379:6379
