version: '3.7'
services:
  frontend:
    container_name: frontend
    restart: unless-stopped
    build: ./frontend
    ports:
      - 3000:3000
    volumes:
      - ~/AppData/Local/pnpm/store:/root/.pnpm-store # MacOS
      # - ~/.pnpm-store:/root/.pnpm-store # Linux

  redis:
    container_name: redis
    image: redis:alpine
    restart: unless-stopped
    volumes:
      - ./redis-db:/data
