version: "3.7"
services:
  canvas-frontend:
    container_name: canvas-frontend
    restart: unless-stopped
    build: ./frontend
    ports:
      - 5173:5173
    env_file:
      - ./frontend/.env
    depends_on:
      - canvas-redis
      - canvas-postgres

  canvas-postgres:
    container_name: canvas-postgres
    restart: unless-stopped
    image: postgres:17.2-alpine3.21
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - ./postgres-db:/var/lib/postgresql/data

  canvas-redis:
    container_name: canvas-redis
    image: redis:7.4.2-alpine
    restart: unless-stopped
    volumes:
      - ./redis-db:/data
    ports:
      - 16379:6379
