version: '3.7'
services:
  frontend:
    container_name: frontend
    image: ghcr.io/pixelcorp-nl/canvas.edu/canvas.edu:latest
    restart: unless-stopped
    ports:
      - 80:5173
    env_file:
      - .env

  redis:
    container_name: redis
    image: redis:alpine
    restart: unless-stopped
    volumes:
      - ./redis-db:/data

  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: frontend
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_INCLUDE_RESTARTING=true
      - WATCHTOWER_POLL_INTERVAL=30
      - WATCHTOWER_ROLLING_RESTART=true
