version: '3.7'
services:
  frontend:
    container_name: frontend
    image: ghcr.io/pixelcorp-nl/canvas.edu/canvas.edu:latest
    restart: unless-stopped
    ports:
      - 80:5173
      - 5174:5174
    env_file:
      - .env

  redis:
    container_name: redis
    image: redis:alpine
    restart: unless-stopped
    volumes:
      - ./redis-db:/data

  datadog-agent:
    container_name: datadog-agent
    image: gcr.io/datadoghq/agent:latest
    pid: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
    env_file: .env
    environment:
      - DD_DOGSTATSD_NON_LOCAL_TRAFFIC=true
    ports:
      - 8125:8125/udp

  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/update-docker-compose.sh:/root/update-docker-compose.sh
    labels:
      - com.centurylinklabs.watchtower.lifecycle.pre-update=/root/update-docker-compose.sh
    command: frontend
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_INCLUDE_RESTARTING=true
      - WATCHTOWER_POLL_INTERVAL=30
      - WATCHTOWER_ROLLING_RESTART=true
