name: Containerize

on:
  push:
    branches:
      - main
      - hotfix/*

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GitHub Package Registry
        uses: docker/login-action@v3
        with:
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Inject GitHub secrets into env
        uses: oNaiPs/secrets-to-env-action@v1
        with:
          secrets: ${{ toJSON(secrets) }}

      - name: Setup .env file
        run: cp .env-example .env

      - name: Build Docker image
        run: docker build -t docker.pkg.github.com/${{ github.repository }}/${{ github.event.repository.name }}:latest .

      - name: Push Docker image to GitHub Package Registry
        run: docker push docker.pkg.github.com/${{ github.repository }}/${{ github.event.repository.name }}:latest
