name: ESLint

on:
  push:
    branches: [ 'main' ]
  pull_request:


jobs:
  style:
    name: run prettier and eslint
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    defaults:
      run:
        working-directory: ./frontend

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install node
      uses: actions/setup-node@v3
      with:
        node-version: 18.x

    - name: Install pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 6.0.2

    - run: pnpm install
    - run: pnpm run build
    - run: pnpm run lint:check
