name: Tests

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    defaults:
      run:
        working-directory: ./frontend

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - uses: docker-practice/actions-setup-docker@master

    - name: Install playwright browsers
      run: npx playwright install --with-deps

    - name: Inject GitHub secrets into env
      uses: oNaiPs/secrets-to-env-action@v1
      with:
        secrets: ${{ toJSON(secrets) }}

    - name: Setup .env file
      run: env >> frontend/.env

    - name: Start services
      run: docker compose up --remove-orphans --build --detach

    - name: Start tests
      run: cd frontend && npm run test
