name: Tests

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Docker buildx
      uses: docker/setup-buildx-action@v3.8.0

    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: latest

    - name: Install make
      run: sudo apt-get install make

    - name: Install playwright package
      run: cd frontend && pnpm i @playwright/test

    - name: Install playwright browsers
      run: cd frontend && npx playwright install chromium

    - name: Inject GitHub secrets into env
      uses: oNaiPs/secrets-to-env-action@v1
      with:
        secrets: ${{ toJSON(secrets) }}

    - name: Setup .env file
      run: cp frontend/.env-example frontend/.env

    - name: Start services
      run: make start-detached

    - name: Wait for services to start
      timeout-minutes: 2
      run: make wait-for-healthcheck

    - name: Run tests
      working-directory:  frontend
      run: npm test -- --reporter=github

    - name: upload playwright artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: playwright-results
        path: frontend/test-results
