name: Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    defaults:
      run:
        working-directory: ./frontend

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Inject GitHub secrets into env
      uses: oNaiPs/secrets-to-env-action@v1
      with:
        secrets: ${{ toJSON(secrets) }}

    - name: Setup .env file
      run: env >> .env

    - name: Install pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 6.0.2

    - name: Install dependencies
      run: pnpm install

    - name: Install playwright browsers
      run: npx playwright install --with-deps

    - name: build
      run: pnpm run build

    - name: check linting
      run: pnpm run lint:check

    - name: Run tests
      run: pnpm run test
