name: Tests

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - uses: docker-practice/actions-setup-docker@master

    - name: Install pnpm
      uses: pnpm/action-setup@v2
      with:
        version: latest

    - name: Install make
      run: sudo apt-get install make

    - name: Install playwright package
      run: cd frontend && pnpm i @playwright/test

    - name: Install playwright browsers
      run: cd frontend && npx playwright install --with-deps

    - name: Inject GitHub secrets into env
      uses: oNaiPs/secrets-to-env-action@v1
      with:
        secrets: ${{ toJSON(secrets) }}

    - name: Setup .env file
      run: env >> frontend/.env

    - name: Start services
      run: make start-detached

    - name: Wait for sercices to start
      run: make wait-for-healthcheck

    - name: Start tests
      run: make test
